[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:edge"

pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update",
    "apt-get install -y --no-install-recommends software-properties-common",
    "add-apt-repository -y ppa:pipewire-debian/pipewire-upstream",
    "apt-get update",
    "apt-get install -y --no-install-recommends libwayland-dev:arm64 libgbm-dev:arm64 libclang-dev libxkbcommon-dev:arm64 libssl-dev:arm64 libpipewire-0.3-dev:arm64 libegl1-mesa-dev:arm64"
]

[target.aarch64-unknown-linux-gnu.env]
PKG_CONFIG_PATH = "/usr/lib/aarch64-linux-gnu/pkgconfig"